### PR TITLE
BCDA-3160: Adding CLM_ID Language to the BCDA Data Dictionary File

### PR DESCRIPTION
**Pull request by jmcconn120**
### Fixes [BCDA-3160](https://jira.cms.gov/browse/BCDA-3160)

GG question that asked why claim unique identifier info was different across FHIR and CCLF. This PR addresses that knowledge gap by explaining that the data fields are not equivalent to one another. 

I added language around CLM_ID to the notes sections each of the rows that contain that data field. (Language: The values displayed for Current Claim Unique Identifier in CCLF files are unique to CCLF. There is no direct 1:1 mapping for  CUR_CLM_UNIQ_ID (CCLF) and CLM_ID (FHIR). ) 

### Security Implications

No. 
- [ ] new software dependencies

- [ ] security controls or supporting software altered

none
- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ ] no PHI/PII is affected by this change

### CODE REVIEW

**Comment by jmcconn120** [comment]
I believe I took everything from master as Liani's workflow document requires?? And I did change the font for the spreadsheet because I saw that there were 3+ fonts in the document so I changed all of the font to make it consistent across the file.

**Comment by msnook** [comment]
> I believe I took everything from master as Liani's workflow document requires?? And I did change the font for the spreadsheet because I saw that there were 3+ fonts in the document so I changed all of the font to make it consistent across the file.

Cool.  I didn't realize there were 3+ fonts.  When I look at it on the website, it looks like `Proxima Nova` is the primary; do we want to continue with that as the primary or move it over to `Times New Roman`?

**Comment by jmcconn120** [comment]
> > I believe I took everything from master as Liani's workflow document requires?? And I did change the font for the spreadsheet because I saw that there were 3+ fonts in the document so I changed all of the font to make it consistent across the file.
> 
> Cool. I didn't realize there were 3+ fonts. When I look at it on the website, it looks like `Proxima Nova` is the primary; do we want to continue with that as the primary or move it over to `Times New Roman`?

Tbh I don't think my version of Excel has Proxima Nova as a font option. So I vote that we just continue with Times New Roman for this Iteration. Its going to be changed again soon.

**Comment by msnook** [comment]
> > > I believe I took everything from master as Liani's workflow document requires?? And I did change the font for the spreadsheet because I saw that there were 3+ fonts in the document so I changed all of the font to make it consistent across the file.
> > 
> > 
> > Cool. I didn't realize there were 3+ fonts. When I look at it on the website, it looks like `Proxima Nova` is the primary; do we want to continue with that as the primary or move it over to `Times New Roman`?
> 
> Tbh I don't think my version of Excel has Proxima Nova as a font option. So I vote that we just continue with Times New Roman for this Iteration. Its going to be changed again soon.

👍

**Pull request merged**
