### PR TITLE
BCDA-2387 Feature: Added test client to user guide

### PR DESCRIPTION
**Pull request by tbellj**
Fixes [BCDA-2387](https://jira.cms.gov/browse/BCDA-2387)

Problem: It's been a concern from our API users that a test client would be helpful for knowing how to interact with our API programmatically. This pr includes a link to our test client that demonstrates all of the steps for API interactions. Requesting a token, making a request, polling for job status, and receiving a fhir payload.

Proposed Changes:
Added an example code link to our test client on the user guide.

Change Details:
production/technical_userguide.md - Added language and a link to our smoke test client (bcda_client.go)
sandbox/technical_user_guide.md - Added language and a link to our smoke test client (bcda_client.go)

Security Implications
No, this change does **not** deal with any PII/PHI data. This is only an update to our static site and no sensitive information is posted.

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

Acceptance Validation
Yes, tested locally.

image

Feedback Requested:
Any and all

### CODE REVIEW

**Comment by epfrankle** [comment]
Agreed with @dhgreene - is that something we can add easily?

**Comment by tbellj** [comment]
We can add that by simply changing the link to this instead: https://github.com/CMSgov/bcda-app/tree/master/test/smoke_test. There they can see the smoke test invocation and the code itself.

**Comment by dhgreene** [comment]
> We can add that by simply changing the link to this instead: https://github.com/CMSgov/bcda-app/tree/master/test/smoke_test. There they can see the smoke test invocation and the code itself.

Linking to the directory gives more info, but also makes it hard to know where to start.  I was thinking of keeping this link as it stands, and adding an example invocation such as:
`go run bcda_client.go -host=$HOSTNAME -clientID=$CLIENT_ID -clientSecret=$CLIENT_SECRET -endpoint=Patient -resourceType=ExplanationOfBenefit`

**Comment by dhgreene** [comment]
We should also probably take out the encryption code before publishing this change.

**Comment by tbellj** [comment]
> > We can add that by simply changing the link to this instead: https://github.com/CMSgov/bcda-app/tree/master/test/smoke_test. There they can see the smoke test invocation and the code itself.
> 
> Linking to the directory gives more info, but also makes it hard to know where to start. I was thinking of keeping this link as it stands, and adding an example invocation such as:
> `go run bcda_client.go -host=$HOSTNAME -clientID=$CLIENT_ID -clientSecret=$CLIENT_SECRET -endpoint=Patient -resourceType=ExplanationOfBenefit`

Im with ya on this will add now

**Comment by tbellj** [comment]
> We should also probably take out the encryption code before publishing this change.

as far as the encryption piece i think it's fine in there, that's another whole separate change in our app repo requiring a ticket which we have in this sprint. Plus, this is only a guide for them not an exact "do this"

**Comment by tbellj** [comment]
New screenshot added! Good idea

**Pull request merged**
