### PR TITLE
BCDA-2941 EOY Changes Ending: Updating static site guide and updates for the runouts feature

### PR DESCRIPTION
**Pull request by Dave-Sukharan**
### Fixes [BCDA-2941](https://jira.cms.gov/browse/BCDA-2941)

BCDA made changes to the API during the runouts period to ensure we could stay on that invalidated many normal calls. These changes were temporary until we retrieved the January attribution file.

Now that the file is received, we must update the guide to its former state but keep the directions on using the 'runout' feature if users need it.

### Proposed Changes

- Rearranged the Building Your Application page and side nav
- Deleted all alerts and notes about "normal" calls to /Patient and /Group not working.
- Added an Update to tell users about return to operations.

### Change Details

The runout directions has been lowered in hierarchy and placed within the Requesting Filtered Data section alongside _since. The section only details how to use runouts with /Group and without _since. The section matches the formatting, headers, and flow of the _since sections.

The Updates page has a new entry for Jan 25 with a brief blurb that we are returning to normal operations using language from the original Google Group post on EOY changes. 

### Security Implications

- [ ] new software dependencies

- [ ] security controls or supporting software altered

- [ ] new data stored or transmitted

- [ ] security checklist is completed for this change

- [ ] requires more information or team discussion to evaluate security implications

- [ X] no PHI/PII is affected by this change

### Acceptance Validation

Screen Shot 2021-01-25 at 2 35 27 PM
Screen Shot 2021-01-25 at 2 35 47 PM
Screen Shot 2021-01-25 at 2 35 58 PM

### Feedback Requested

- Do you agree with dropping the runouts data into the Requesting Filtered Data parent section?
- Does the language in the new runouts data section read as you would expect it?
- Does the Update read as expected?
- Should we include using runouts and _since together?

### CODE REVIEW

**Review by epfrankle — DISMISSED** [review]
Made some minor changes to add internal links and standardize language. Nice work @Dave-Sukharan!

**Review by mtrang1263 — COMMENTED** [review]
Can we rename `_includes/build/requesting_data_EOY.html` to `_includes/build/requesting_data_runout.html`

Also updating all the other references to the new file name as well

**Comment by Dave-Sukharan** [comment]
I made that slight change to the file names, @mtrang1263. I also deleted some of the old files we needed cleaned-up. Let me know if this can be merged in or if we should leave off the last commit

**Comment by mtrang1263** [comment]
LGTM! Would you  mind updating the PR title? Maybe you can link it to one of the JIRA ticket(s)?

**Review by mtrang1263 — APPROVED** [review]

**Pull request merged**
